---
title: "Гістограми"
---

```{r, echo = FALSE}
knitr::opts_chunk$set(fig.retina=2, fig.path = "fig_histograms_dyn/")
```

В продовження до попередньої статті &laquo;[Динаміка поширення
коронавірусної інфекції по областях](regions_dyn.html)&raquo; побудуємо гістограми.


## Дні, коли найбільше та найменше реєструють

```{r, message = FALSE, results='hide'}
library(tidyverse)
Sys.setlocale(category="LC_ALL",locale="uk_UA.utf8" )
```

```{r}
area_dyn <- read_csv('../covid19_by_area_type_hosp_dynamics.csv')
```

```{r}
area_dyn <- area_dyn %>%
    mutate(Weekday_Num = factor(strftime(zvit_date, format="%u"))) %>%
    mutate(Weekday_Name = factor(case_when(
               Weekday_Num == "1" ~ "Понеділок",
               Weekday_Num == "2" ~ "Вівторок",
               Weekday_Num == "3" ~ "Середа",
               Weekday_Num == "4" ~ "Четвер",
               Weekday_Num == "5" ~ "П'ятниця",
               Weekday_Num == "6" ~ "Субота",
               Weekday_Num == "7" ~ "Неділя",
               TRUE ~ "etc")))
```

```{r}
dyn_by_day <- area_dyn %>%
    select(Weekday_Name, Weekday_Num, new_susp, new_confirm, new_death) %>%
    group_by(Weekday_Name) %>%
    summarise(Weekday_Num = first(Weekday_Num),
              new_susp = sum(new_susp),
              new_confirm = sum(new_confirm),
              new_death = sum(new_death))
```

## Підозри

```{r}
(ggplot(dyn_by_day, aes(x=Weekday_Num, y=new_susp))
    + geom_bar(stat="identity"))
```

## Підтверджених випадків

```{r}
(ggplot(dyn_by_day,
        aes(fct_reorder(Weekday_Name, Weekday_Num,
                        .fun=identity, .desc=FALSE),
            new_confirm))
    + geom_bar(stat="identity")
    + theme_light())
```

## Смертей

```{r}
(ggplot(dyn_by_day, aes(x=Weekday_Num, y=new_death))
    + geom_bar(stat="identity")
    + theme_light())
```

[Повернутись на головну](index.html) або [повідомити про
помилку]((https://github.com/vityok/covid19_ua/issues))
